# Generated by Django 4.1.3 on 2022-11-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('client_name', models.CharField(max_length=200)),
                ('client_surname', models.CharField(max_length=200)),
                ('order_date', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
